apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
  labels:
   test: MyExampleApp
spec:
  replicas: 2
  selector:
    matchLabels:
      test: MyExampleApp
  template:
    metadata:
      labels:
        test: MyExampleApp
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: app
        image: gjoshevski/aks-pod-info
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: AZURE_SUBSCRIPTION_ID
          value: "80beae50-8fde-4c7e-9fe0-d328d4b6b84d"
        - name: AZURE_SERVICE_PRINCIPAL_OBJECT_ID
          value: "9ec8180f-ae97-47a5-8aed-7de11f55716d"